[package]
name = "tf2noisemaker"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.1"
sysinfo = "0.30"
windows = { version = "0.56", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }